-- "lua\\autorun\\simoncostumes.lua"
-- Retrieved by https://github.com/lewisclark/glua-steal
player_manager.AddValidModel( "simon", "models/gonzo/simoncostumes/simon/simon.mdl" ) 
player_manager.AddValidModel( "simonaom", "models/gonzo/simoncostumes/simonaom/simonaom.mdl" ) 
player_manager.AddValidModel( "simonawesome", "models/gonzo/simoncostumes/simonawesome/simonawesome.mdl" ) 
player_manager.AddValidModel( "simonblackmetal", "models/gonzo/simoncostumes/simonblackmetal/simonblackmetal.mdl" ) 
player_manager.AddValidModel( "simonbooksimon", "models/gonzo/simoncostumes/simonbooksimon/simonbooksimon.mdl" ) 
player_manager.AddValidModel( "simoncamo", "models/gonzo/simoncostumes/simoncamo/simoncamo.mdl" ) 
player_manager.AddValidModel( "simonhcl", "models/gonzo/simoncostumes/simonhcl/simonhcl.mdl" ) 
player_manager.AddValidModel( "simonhellokitty", "models/gonzo/simoncostumes/simonhellokitty/simonhellokitty.mdl" ) 
player_manager.AddValidModel( "simonleatherhoff", "models/gonzo/simoncostumes/simonleatherhoff/simonleatherhoff.mdl" ) 
player_manager.AddValidModel( "simonmoddb", "models/gonzo/simoncostumes/simonmoddb/simonmoddb.mdl" ) 
player_manager.AddValidModel( "simonsicksimon", "models/gonzo/simoncostumes/simonsicksimon/simonsicksimon.mdl" ) 
player_manager.AddValidModel( "simonteampsyskallar", "models/gonzo/simoncostumes/simonteampsyskallar/simonteampsyskallar.mdl" ) 
player_manager.AddValidModel( "simontwitcher", "models/gonzo/simoncostumes/simontwitcher/simontwitcher.mdl" ) 

player_manager.AddValidHands( "simon", "models/gonzo/simoncostumes/simon/simonhands.mdl", 0, "00000000" )
player_manager.AddValidHands( "simonaom", "models/gonzo/simoncostumes/simonaom/simonaomhands.mdl", 0, "00000000" )
player_manager.AddValidHands( "simonawesome", "models/gonzo/simoncostumes/simonawesome/simonawesomehands.mdl", 0, "00000000" )
player_manager.AddValidHands( "simonblackmetal", "models/gonzo/simoncostumes/simonblackmetal/simonblackmetalhands.mdl", 0, "00000000" )
player_manager.AddValidHands( "simonbooksimon", "models/gonzo/simoncostumes/simonbooksimon/simonbooksimonhands.mdl", 0, "00000000" )
player_manager.AddValidHands( "simoncamo", "models/gonzo/simoncostumes/simoncamo/simoncamohands.mdl", 0, "00000000" )
player_manager.AddValidHands( "simonhcl", "models/gonzo/simoncostumes/simonhcl/simonhclhands.mdl", 0, "00000000" )
player_manager.AddValidHands( "simonhellokitty", "models/gonzo/simoncostumes/simonhellokitty/simonhellokittyhands.mdl", 0, "00000000" )
player_manager.AddValidHands( "simonleatherhoff", "models/gonzo/simoncostumes/simonleatherhoff/simonleatherhoffhands.mdl", 0, "00000000" )
player_manager.AddValidHands( "simonmoddb", "models/gonzo/simoncostumes/simonmoddb/simonmoddbhands.mdl", 0, "00000000" )
player_manager.AddValidHands( "simonsicksimon", "models/gonzo/simoncostumes/simonsicksimon/simonsicksimonhands.mdl", 0, "00000000" )
player_manager.AddValidHands( "simonteampsyskallar", "models/gonzo/simoncostumes/simonteampsyskallar/simonteampsyskallarhands.mdl", 0, "00000000" )
player_manager.AddValidHands( "simontwitcher", "models/gonzo/simoncostumes/simontwitcher/simontwitcherhands.mdl", 0, "00000000" )

list.Set( "PlayerOptionsModel",  "simon", "models/gonzo/simoncostumes/simon/simon.mdl" )
list.Set( "PlayerOptionsModel", "simonaom", "models/gonzo/simoncostumes/simonaom/simonaom.mdl" ) 
list.Set( "PlayerOptionsModel", "simonawesome", "models/gonzo/simoncostumes/simonawesome/simonawesome.mdl" ) 
list.Set( "PlayerOptionsModel", "simonblackmetal", "models/gonzo/simoncostumes/simonblackmetal/simonblackmetal.mdl" ) 
list.Set( "PlayerOptionsModel", "simonbooksimon", "models/gonzo/simoncostumes/simonbooksimon/simonbooksimon.mdl" ) 
list.Set( "PlayerOptionsModel", "simoncamo", "models/gonzo/simoncostumes/simoncamo/simoncamo.mdl" ) 
list.Set( "PlayerOptionsModel", "simonhcl", "models/gonzo/simoncostumes/simonhcl/simonhcl.mdl" ) 
list.Set( "PlayerOptionsModel", "simonhellokitty", "models/gonzo/simoncostumes/simonhellokitty/simonhellokitty.mdl" ) 
list.Set( "PlayerOptionsModel", "simonleatherhoff", "models/gonzo/simoncostumes/simonleatherhoff/simonleatherhoff.mdl" ) 
list.Set( "PlayerOptionsModel", "simonmoddb", "models/gonzo/simoncostumes/simonmoddb/simonmoddb.mdl" ) 
list.Set( "PlayerOptionsModel", "simonsicksimon", "models/gonzo/simoncostumes/simonsicksimon/simonsicksimon.mdl" ) 
list.Set( "PlayerOptionsModel", "simonteampsyskallar", "models/gonzo/simoncostumes/simonteampsyskallar/simonteampsyskallar.mdl" ) 
list.Set( "PlayerOptionsModel", "simontwitcher", "models/gonzo/simoncostumes/simontwitcher/simontwitcher.mdl" ) 